spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/workbatch_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
app:
  application:
    name: app
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: 123456
    username: root
logging:
  config: classpath:log4j.xml
#logging:
#  level:
#    root: INFO
#    org.springframework.batch: DEBUG
#    org.springframework.jdbc: DEBUG